Models/ErrorViewModel.cs
namespace sporKlubuApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/dbcontext.cs
using Microsoft.EntityFrameworkCore;
using sporKlubuApp.Models;
 
public class DataContext : DbContext
{
    protected readonly IConfiguration Configuration;
 
    public DataContext(IConfiguration configuration)
    {
        Configuration = configuration;
    }
 
    protected override void OnConfiguring(DbContextOptionsBuilder options)
    {
        // appsettings.js içinde belirtilen sql servere bağlan
        options.UseSqlServer(Configuration.GetConnectionString("filmCnnStr"));
    }
// veritabanına Film nesnesini Filmler tablosu olarak ekliyoruz
    public DbSet<Uye> Uyeler { get; set; }
}

Models/uyeler.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

public class Uye{
    
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }
    
    [Display(Name ="Ad")]
    [Required(ErrorMessage ="Ad boş bırakılamaz")]
    public string   Ad { get; set; }

    [Display(Name ="Soyad")]
    [Required(ErrorMessage ="Soyad boş bırakılamaz")]
    public string   Soyad { get; set; }

    [Display(Name ="Email")]
    [Required(ErrorMessage ="Email boş bırakılamaz")]
    [EmailAddress]
    public string   Email { get; set; }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using sporKlubuApp.Models;

namespace sporKlubuApp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/UyeController.cs
using Microsoft.AspNetCore.Mvc;
//using sporKlubuApp.Models;

namespace sporKlubuApp.Controllers
{
    public class UyeController : Controller
    {
        //Veritabanı nesnesini kontroller başlangıcına enjekte ediyoruz
        private DataContext _context;
        public UyeController(DataContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {//veritabanı örneğinden üyeler listesini çekiyoruz
            List<Uye> uyeler = _context.Uyeler.ToList();
            return View(uyeler);
        }

        public IActionResult Ekle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Ekle(Uye model)
        {
            //model geçerli ise; eksik bilgi veya geçersiz bilgi yok ise
            if (ModelState.IsValid)
            {
                //db örneğindeki üye listesine ekle
                _context.Uyeler.Add(model);
                //veritabanı örneğini veritabanına kaydet, veritabanını güncelle
                _context.SaveChanges();
                //uye listesine dön
                return RedirectToAction(nameof(Index));
            }
            //eğer model geçersiz ise  hataların olduğu hali ile kullanıcıya tekrar göster
            return View();
        }

        public IActionResult Sil(int id)
        {
            //silinecek kaydı bul
            Uye silinecek = _context.Uyeler.Find(id);
            //eğer silinecek kayıt veritabanına var ise
            if (silinecek != null)
            {
                //veritabanından sil
                _context.Remove(silinecek);
                //veritabanını güncelle
                _context.SaveChanges();
            }
            //listeye yönlendir
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Duzenle(int? id)
        {
            if (id.HasValue)
            {
                Uye aranan = _context.Uyeler.Find(id);
                if (aranan != null)
                {
                    return View(aranan);
                }
                //eğer aranan id ile kayıt yok ise 404 ver
                return NotFound();
            }
            //eğer id gelmedi ise 404 ver
            return NotFound();

        }
        [HttpPost]
        public IActionResult Duzenle(Uye m)
        {
            
            if (ModelState.IsValid)
            {
                _context.Uyeler.Update(m);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Spor Kulübü</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/sporKlubuApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">sporKlubuApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                            asp-controller="Uye" 
                            asp-action="Index">Üyeler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" 
                            asp-controller="Uye" 
                            asp-action="Ekle">Üye Ekle</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - sporKlubuApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Uye/Duzenle.cshtml
@using sporKlubuApp.Models
@model Uye
@{ ViewBag.Title="Düzenle";}
<form asp-antiforgery="true">
    <div class="row">
        <input type="hidden" asp-for="Id" />
        <div class="col-3">
            <label asp-for="Ad" class="control-label"></label>
        </div>
        <div class="col-9">
            <input asp-for="Ad" class="form-control">
            <span asp-validation-for="Ad" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-3">
            <label asp-for="Soyad" class="control-label"></label>
        </div>
        <div class="col-9">
            <input asp-for="Soyad" class="form-control">
            <span asp-validation-for="Soyad" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-3">
            <label asp-for="Email" class="control-label"></label>
        </div>
        <div class="col-9">
            <input asp-for="Email" class="form-control">
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <button type="submit" class="btn-primary btn">Kaydet</button>
        <button type="reset" class="btn-danger btn">Sıfırla</button>

    </div>
</form>
@section Scripts{
<partial name="_ValidationScriptsPartial" />
}

Views/Uye/Ekle.cshtml
@using sporKlubuApp.Models
@model Uye

<form asp-antiforgery="true">
    <div class="row">
        <div class="col-3">
            <label asp-for="Ad" class="control-label"></label>
        </div>
        <div class="col-9">
            <input asp-for="Ad" class="form-control">
            <span asp-validation-for="Ad" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-3">
            <label asp-for="Soyad" class="control-label"></label>
        </div>
        <div class="col-9">
            <input asp-for="Soyad" class="form-control">
            <span asp-validation-for="Soyad" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-3">
            <label asp-for="Email" class="control-label"></label>
        </div>
        <div class="col-9">
            <input asp-for="Email" class="form-control">
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <button type="submit" class="btn-primary btn">Kaydet</button>
        <button type="reset" class="btn-danger btn">Sıfırla</button>
        
    </div>
</form>
@section Scripts{
    <partial name="_ValidationScriptsPartial"/>
}

Views/Uye/Index.cshtml
@using sporKlubuApp.Models;
@model List<Uye>
@foreach (var item in Model)
{
    <div class="row mb-1">
        <div class="col-3">@item.Ad</div>
        <div class="col-3">@item.Soyad</div>
        <div class="col-3">@item.Email</div>
        <div class="col-3">
            <a class="btn btn-danger sil" asp-action="Sil" 
            asp-route-id="@item.Id">
                <i class="bi bi-trash-fill"></i>
            </a>
            <a asp-action="Duzenle" class="btn-primary btn" 
            asp-route-id="@item.Id" title="Düzenle">
               <i class="bi bi-pencil-square"></i>
            </a>
        </div>

    </div>
}
@section Scripts{
<script>
    $(".sil").click(function () {
        return confirm("Silmek istediğinizden emin misiniz?");
    })
</script>
}